(() => {
  const URL='https://fljoowkjmvqijqiaimpp.supabase.co',KEY='sb_publishable_YdE-PNM_SrerYvKjBn68BQ_8YCpuKR9',API=`${URL}/functions/v1/admin-api`;
  const $=id=>document.getElementById(id),uid=new URLSearchParams(location.search).get('uid');
  const token=()=>sessionStorage.getItem('filaments_admin_token')||'';let data=null,editing=null;
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
  async function call(action,body={}){const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json','apikey':KEY,'x-admin-token':token()},body:JSON.stringify({action,...body})});const d=await r.json();if(!r.ok)throw new Error(d.message||d.error||'Request failed');return d}
  const grams=v=>Number(v||0)>=1000?`${(Number(v)/1000).toFixed(2)} kg`:`${Math.round(Number(v||0))} g`;
  function mountedName(id){return data?.spools?.find(s=>s.id===id)?.name||'—'}
  function render(){const u=data.user,sp=data.spools||[],pr=data.printers||[],lg=data.usage_logs||[],remaining=sp.reduce((a,x)=>a+Number(x.remaining_weight||0),0),usage=lg.reduce((a,x)=>a+Number(x.grams_used||0),0);$('userTitle').textContent=u.nickname?`${u.nickname} · ${u.email}`:u.email;$('userSub').textContent=`ID: ${u.id} · Created: ${new Date(u.created_at).toLocaleString()} · Last sign in: ${u.last_sign_in_at?new Date(u.last_sign_in_at).toLocaleString():'—'}`;$('dSpools').textContent=sp.length;$('dPrinters').textContent=pr.length;$('dRemaining').textContent=grams(remaining);$('dUsage').textContent=grams(usage);$('accountInfo').innerHTML=`<div><b>Email:</b> ${esc(u.email)}</div><div><b>Nickname:</b> ${esc(u.nickname||'—')}</div><div><b>Current page:</b> ${esc(u.presence?.current_page||'—')}</div><div><b>Last activity:</b> ${u.presence?.last_seen?new Date(u.presence.last_seen).toLocaleString():'—'}</div>`;$('recentSpools').innerHTML=sp.slice(0,6).map(spoolCard).join('')||'<div class="muted">No spools.</div>';$('spoolCards').innerHTML=sp.map(spoolCard).join('')||'<div class="muted">No spools.</div>';$('printerCards').innerHTML=pr.map(printerCard).join('')||'<div class="muted">No printers.</div>';$('usageBody').innerHTML=lg.map(x=>`<tr><td>${new Date(x.created_at).toLocaleString()}</td><td>${esc(mountedName(x.spool_id))}</td><td>${esc(pr.find(p=>p.id===x.printer_id)?.name||'—')}</td><td>${grams(x.grams_used)}</td><td>${esc(x.source||'—')}</td><td>${esc(x.note||'—')}</td></tr>`).join('')||'<tr><td colspan="6">No usage records.</td></tr>';$('ticketCards').innerHTML=(data.tickets||[]).map(x=>`<div class="card"><h3>Ticket #${x.ticket_no}</h3><div>${esc(x.kind)} · ${esc(x.status)}</div><div class="muted">${new Date(x.created_at).toLocaleString()}</div><p>${esc(x.message)}</p></div>`).join('')||'<div class="muted">No tickets.</div>';document.querySelectorAll('.edit-spool').forEach(b=>b.onclick=()=>openSpool(b.dataset.id));document.querySelectorAll('.edit-printer').forEach(b=>b.onclick=()=>openPrinter(b.dataset.id))}
  function spoolCard(s){const pct=Math.max(0,Math.min(100,Number(s.total_weight)?Number(s.remaining_weight||0)/Number(s.total_weight)*100:0));return `<div class="card"><h3><span class="sw" style="background:${esc(s.color_hex||'#808080')}"></span>${esc(s.name)}</h3><div class="muted">${esc(s.brand||'—')} · ${esc(s.material||'—')} · ${esc(s.color||'—')}</div><div style="font-size:22px;font-weight:900;margin-top:8px">${grams(s.remaining_weight)} / ${grams(s.total_weight)}</div><div class="bar"><i style="width:${pct}%"></i></div><div class="muted">${Math.round(pct)}% · ${esc(s.location_name||s.location||'Warehouse')}</div><button class="btn secondary edit-spool" data-id="${s.id}" style="margin-top:10px">Edit</button></div>`}
  function printerCard(p){return `<div class="card"><h3>${esc(p.name)}</h3><div class="muted">${esc(p.model||'No model')}</div><div style="margin-top:8px"><b>Status:</b> ${esc(p.status||'idle')}</div><div><b>Loaded spool:</b> ${esc(mountedName(p.loaded_spool_id))}</div><div><b>Location:</b> ${esc(p.location_name||'—')}</div><button class="btn secondary edit-printer" data-id="${p.id}" style="margin-top:10px">Edit</button></div>`}
  function field(name,label,value,type='text',full=false){return `<label class="${full?'full':''}">${label}<input name="${name}" type="${type}" value="${esc(value??'')}"></label>`}
  function openSpool(id){const s=data.spools.find(x=>x.id===id);editing={type:'spool',id};$('editTitle').textContent=`Edit spool · ${s.name}`;$('editForm').innerHTML=field('name','Name',s.name)+field('brand','Brand',s.brand)+field('material','Material',s.material)+field('color','Color name',s.color)+field('color_hex','Color hex',s.color_hex)+field('total_weight','Total weight (g)',s.total_weight,'number')+field('remaining_weight','Remaining (g)',s.remaining_weight,'number')+field('purchase_price','Price',s.purchase_price,'number')+field('location_name','Location',s.location_name)+field('lot_nr','Lot',s.lot_nr)+field('article_number','SKU',s.article_number)+field('diameter','Diameter',s.diameter,'number')+field('density','Density',s.density,'number')+field('nozzle_min','Nozzle min',s.nozzle_min,'number')+field('nozzle_max','Nozzle max',s.nozzle_max,'number')+field('bed_min','Bed min',s.bed_min,'number')+field('bed_max','Bed max',s.bed_max,'number')+`<label class="full">Notes<textarea name="notes" rows="4">${esc(s.notes||'')}</textarea></label>`;$('editModal').classList.add('show')}
  function openPrinter(id){const p=data.printers.find(x=>x.id===id);editing={type:'printer',id};$('editTitle').textContent=`Edit printer · ${p.name}`;$('editForm').innerHTML=field('name','Name',p.name)+field('model','Model',p.model)+`<label>Status<select name="status"><option value="idle" ${p.status==='idle'?'selected':''}>Idle</option><option value="printing" ${p.status==='printing'?'selected':''}>Printing</option><option value="maintenance" ${p.status==='maintenance'?'selected':''}>Maintenance</option><option value="offline" ${p.status==='offline'?'selected':''}>Offline</option></select></label>`+field('location_name','Location',p.location_name)+`<label class="full">Notes<textarea name="notes" rows="4">${esc(p.notes||'')}</textarea></label>`;$('editModal').classList.add('show')}
  async function saveEdit(){if(!editing)return;const fd=new FormData($('editForm')),patch={};for(const [k,v] of fd.entries()){if(['total_weight','remaining_weight','purchase_price','diameter','density','nozzle_min','nozzle_max','bed_min','bed_max'].includes(k))patch[k]=v===''?null:Number(v);else patch[k]=v}await call(editing.type==='spool'?'update_spool':'update_printer',{id:editing.id,user_id:uid,patch});$('editModal').classList.remove('show');await load()}
  async function load(){if(!uid||!token())return location.href='/admin.html';try{data=await call('user_detail',{user_id:uid});render()}catch(e){alert(e.message);if(e.message==='unauthorized')location.href='/admin.html'}}
  function init(){document.querySelectorAll('.nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));$(`${b.dataset.page}Page`).classList.add('active')});$('backAdmin').onclick=()=>location.href='/admin.html';$('refreshUser').onclick=load;$('editClose').onclick=()=>$('editModal').classList.remove('show');$('editSave').onclick=saveEdit;load()}init();
})();