(() => {
  const URL='https://fljoowkjmvqijqiaimpp.supabase.co',KEY='sb_publishable_YdE-PNM_SrerYvKjBn68BQ_8YCpuKR9',API=`${URL}/functions/v1/admin-api`;
  const $=id=>document.getElementById(id),uid=new URLSearchParams(location.search).get('uid');
  const token=()=>sessionStorage.getItem('filaments_admin_token')||'';let data=null,editing=null,timerLoop=null;
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  async function call(action,body={}){const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json','apikey':KEY,'x-admin-token':token()},body:JSON.stringify({action,...body})});const d=await r.json();if(!r.ok)throw new Error(d.message||d.error||'Request failed');return d}
  const grams=v=>Number(v||0)>=1000?`${(Number(v)/1000).toFixed(2)} kg`:`${Math.round(Number(v||0))} g`;
  function mountedName(id){return data?.spools?.find(s=>s.id===id)?.name||'—'}
  function fmtDuration(ms){ms=Math.max(0,Number(ms)||0);const total=Math.floor(ms/1000),d=Math.floor(total/86400),h=Math.floor((total%86400)/3600),m=Math.floor((total%3600)/60),s=total%60;if(d>0)return `${d}d ${h}h ${m}m`;if(h>0)return `${h}h ${m}m ${s}s`;return `${m}m ${s}s`}
  function timerHtml(p){
    if(p.status!=='printing'||!p.print_ends_at)return '';
    const end=new Date(p.print_ends_at).getTime(); if(!Number.isFinite(end))return '';
    const start=p.print_started_at?new Date(p.print_started_at).getTime():end-Math.max(0,Number(p.print_duration_minutes||0))*60000;
    const now=Date.now(),total=Math.max(1,end-start),left=Math.max(0,end-now),elapsed=Math.max(0,Math.min(total,now-start)),pct=Math.max(0,Math.min(100,elapsed/total*100));
    return `<div class="admin-print-timer" style="margin-top:10px;padding:10px;border:1px solid var(--line);background:var(--card2);border-radius:12px"><div style="display:flex;justify-content:space-between;gap:10px;align-items:center"><b>⏱ ${fmtDuration(left)} remaining</b><span class="muted">${Math.round(pct)}%</span></div><div class="bar"><i style="width:${pct}%"></i></div><div class="muted" style="font-size:11px;line-height:1.7"><div><b>Started:</b> ${Number.isFinite(start)?new Date(start).toLocaleString():'—'}</div><div><b>Ends:</b> ${new Date(end).toLocaleString()}</div><div><b>Elapsed:</b> ${fmtDuration(elapsed)}</div><div><b>Planned duration:</b> ${p.print_duration_minutes?`${p.print_duration_minutes} min`:'—'}</div></div></div>`
  }
  function renderPrinterCards(){const box=$('printerCards');if(!box||!data)return;box.innerHTML=(data.printers||[]).map(printerCard).join('')||'<div class="muted">No printers.</div>';document.querySelectorAll('.edit-printer').forEach(b=>b.onclick=()=>openPrinter(b.dataset.id))}
  function render(){const u=data.user,sp=data.spools||[],pr=data.printers||[],lg=data.usage_logs||[],remaining=sp.reduce((a,x)=>a+Number(x.remaining_weight||0),0),usage=lg.reduce((a,x)=>a+Number(x.grams_used||0),0);$('userTitle').textContent=u.nickname?`${u.nickname} · ${u.email}`:u.email;$('userSub').textContent=`ID: ${u.id} · Created: ${new Date(u.created_at).toLocaleString()} · Last sign in: ${u.last_sign_in_at?new Date(u.last_sign_in_at).toLocaleString():'—'}`;$('dSpools').textContent=sp.length;$('dPrinters').textContent=pr.length;$('dRemaining').textContent=grams(remaining);$('dUsage').textContent=grams(usage);$('accountInfo').innerHTML=`<div><b>Email:</b> ${esc(u.email)}</div><div><b>Nickname:</b> ${esc(u.nickname||'—')}</div><div><b>Current page:</b> ${esc(u.presence?.current_page||'—')}</div><div><b>Last activity:</b> ${u.presence?.last_seen?new Date(u.presence.last_seen).toLocaleString():'—'}</div>`;$('recentSpools').innerHTML=sp.slice(0,6).map(spoolCard).join('')||'<div class="muted">No spools.</div>';$('spoolCards').innerHTML=sp.map(spoolCard).join('')||'<div class="muted">No spools.</div>';renderPrinterCards();$('usageBody').innerHTML=lg.map(x=>`<tr><td>${new Date(x.created_at).toLocaleString()}</td><td>${esc(mountedName(x.spool_id))}</td><td>${esc(pr.find(p=>p.id===x.printer_id)?.name||'—')}</td><td>${grams(x.grams_used)}</td><td>${esc(x.source||'—')}</td><td>${esc(x.note||'—')}</td></tr>`).join('')||'<tr><td colspan="6">No usage records.</td></tr>';$('ticketCards').innerHTML=(data.tickets||[]).map(x=>`<div class="card"><h3>Ticket #${x.ticket_no}</h3><div>${esc(x.kind)} · ${esc(x.status)}</div><div class="muted">${new Date(x.created_at).toLocaleString()}</div><p>${esc(x.message)}</p></div>`).join('')||'<div class="muted">No tickets.</div>';document.querySelectorAll('.edit-spool').forEach(b=>b.onclick=()=>openSpool(b.dataset.id))}
  function spoolCard(s){const pct=Math.max(0,Math.min(100,Number(s.total_weight)?Number(s.remaining_weight||0)/Number(s.total_weight)*100:0));return `<div class="card"><h3><span class="sw" style="background:${esc(s.color_hex||'#808080')}"></span>${esc(s.name)}</h3><div class="muted">${esc(s.brand||'—')} · ${esc(s.material||'—')} · ${esc(s.color||'—')}</div><div style="font-size:22px;font-weight:900;margin-top:8px">${grams(s.remaining_weight)} / ${grams(s.total_weight)}</div><div class="bar"><i style="width:${pct}%"></i></div><div class="muted">${Math.round(pct)}% · ${esc(s.location_name||s.location||'Warehouse')}</div><button class="btn secondary edit-spool" data-id="${s.id}" style="margin-top:10px">Edit</button></div>`}
  function printerCard(p){return `<div class="card"><h3>${esc(p.name)}</h3><div class="muted">${esc(p.model||'No model')}</div><div style="margin-top:8px"><b>Status:</b> ${esc(p.status||'idle')}</div><div><b>Loaded spool:</b> ${esc(mountedName(p.loaded_spool_id))}</div><div><b>Location:</b> ${esc(p.location_name||'—')}</div>${timerHtml(p)}<button class="btn secondary edit-printer" data-id="${p.id}" style="margin-top:10px">Edit</button></div>`}
  function field(name,label,value,type='text',full=false){return `<label class="${full?'full':''}">${label}<input name="${name}" type="${type}" value="${esc(value??'')}"></label>`}
  function openSpool(id){const s=data.spools.find(x=>x.id===id);editing={type:'spool',id};$('editTitle').textContent=`Edit spool · ${s.name}`;$('editForm').innerHTML=field('name','Name',s.name)+field('brand','Brand',s.brand)+field('material','Material',s.material)+field('color','Color name',s.color)+field('color_hex','Color hex',s.color_hex)+field('total_weight','Total weight (g)',s.total_weight,'number')+field('remaining_weight','Remaining (g)',s.remaining_weight,'number')+field('purchase_price','Price',s.purchase_price,'number')+field('location_name','Location',s.location_name)+field('lot_nr','Lot',s.lot_nr)+field('article_number','SKU',s.article_number)+field('diameter','Diameter',s.diameter,'number')+field('density','Density',s.density,'number')+field('nozzle_min','Nozzle min',s.nozzle_min,'number')+field('nozzle_max','Nozzle max',s.nozzle_max,'number')+field('bed_min','Bed min',s.bed_min,'number')+field('bed_max','Bed max',s.bed_max,'number')+`<label class="full">Notes<textarea name="notes" rows="4">${esc(s.notes||'')}</textarea></label>`;$('editModal').classList.add('show')}
  function remainingParts(p){if(p.status!=='printing'||!p.print_ends_at)return{h:0,m:0};const mins=Math.max(0,Math.ceil((new Date(p.print_ends_at).getTime()-Date.now())/60000));return{h:Math.floor(mins/60),m:mins%60}}
  function openPrinter(id){const p=data.printers.find(x=>x.id===id),rm=remainingParts(p);editing={type:'printer',id};$('editTitle').textContent=`Edit printer · ${p.name}`;$('editForm').innerHTML=field('name','Name',p.name)+field('model','Model',p.model)+`<label>Status<select name="status" id="adminPrinterStatus"><option value="idle" ${p.status==='idle'?'selected':''}>Idle</option><option value="printing" ${p.status==='printing'?'selected':''}>Printing</option><option value="maintenance" ${p.status==='maintenance'?'selected':''}>Maintenance</option><option value="offline" ${p.status==='offline'?'selected':''}>Offline</option></select></label>`+field('location_name','Location',p.location_name)+`<div id="adminTimeBox" class="full" style="padding:12px;border:1px solid var(--line);border-radius:12px;background:var(--card2)"><b>⏱ Edit remaining print time</b><div style="display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:8px">${field('admin_remaining_hours','Remaining hours',rm.h,'number')}${field('admin_remaining_minutes','Remaining minutes',rm.m,'number')}</div><div id="adminEndPreview" class="muted" style="margin-top:8px;font-size:12px"></div></div><label class="full">Notes<textarea name="notes" rows="4">${esc(p.notes||'')}</textarea></label>`;$('editModal').classList.add('show');const st=$('adminPrinterStatus'),form=$('editForm');const sync=()=>{const box=$('adminTimeBox');if(box)box.style.display=st?.value==='printing'?'block':'none';const h=Math.max(0,Number(form?.elements?.admin_remaining_hours?.value||0)),m=Math.max(0,Math.min(59,Number(form?.elements?.admin_remaining_minutes?.value||0)));const mins=Math.round(h*60+m),out=$('adminEndPreview');if(out)out.textContent=mins>0?`New expected end: ${new Date(Date.now()+mins*60000).toLocaleString()}`:'Enter a remaining time.'};st?.addEventListener('change',sync);form?.elements?.admin_remaining_hours?.addEventListener('input',sync);form?.elements?.admin_remaining_minutes?.addEventListener('input',sync);sync()}
  async function saveEdit(){if(!editing)return;const fd=new FormData($('editForm')),patch={};for(const [k,v] of fd.entries()){if(k.startsWith('admin_'))continue;if(['total_weight','remaining_weight','purchase_price','diameter','density','nozzle_min','nozzle_max','bed_min','bed_max'].includes(k))patch[k]=v===''?null:Number(v);else patch[k]=v}
    if(editing.type==='printer'){
      const p=data.printers.find(x=>x.id===editing.id),status=String(patch.status||'idle');
      if(status==='printing'){
        const h=Math.max(0,Math.floor(Number(fd.get('admin_remaining_hours')||0))),m=Math.max(0,Math.min(59,Math.floor(Number(fd.get('admin_remaining_minutes')||0)))),remaining=h*60+m;
        if(remaining<=0)return alert('Enter remaining print time.');
        const now=Date.now(),oldStart=p?.print_started_at?new Date(p.print_started_at).getTime():NaN,start=Number.isFinite(oldStart)&&oldStart<=now?oldStart:now,elapsed=Math.max(0,Math.round((now-start)/60000));
        patch.print_started_at=new Date(start).toISOString();patch.print_ends_at=new Date(now+remaining*60000).toISOString();patch.print_duration_minutes=elapsed+remaining;
      }else{patch.print_started_at=null;patch.print_ends_at=null;patch.print_duration_minutes=null}
    }
    await call(editing.type==='spool'?'update_spool':'update_printer',{id:editing.id,user_id:uid,patch});$('editModal').classList.remove('show');await load()}
  async function load(){if(!uid||!token())return location.href='/admin.html';try{data=await call('user_detail',{user_id:uid});render()}catch(e){alert(e.message);if(e.message==='unauthorized')location.href='/admin.html'}}
  function startTimerLoop(){if(timerLoop)clearInterval(timerLoop);timerLoop=setInterval(()=>{if(!document.hidden&&data&&$('printersPage')?.classList.contains('active'))renderPrinterCards()},1000)}
  function init(){document.querySelectorAll('.nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));$(`${b.dataset.page}Page`).classList.add('active');if(b.dataset.page==='printers')renderPrinterCards()});$('backAdmin').onclick=()=>location.href='/admin.html';$('refreshUser').onclick=load;$('editClose').onclick=()=>$('editModal').classList.remove('show');$('editSave').onclick=saveEdit;startTimerLoop();load()}init();
})();