(() => {
  const URL='https://fljoowkjmvqijqiaimpp.supabase.co',KEY='sb_publishable_YdE-PNM_SrerYvKjBn68BQ_8YCpuKR9',API=`${URL}/functions/v1/admin-api`;
  const $=id=>document.getElementById(id); const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
  let users=[],feedback=[],prefs={},lang='en',currentTicket=null,baseline=null;
  const TR={en:{totalUsers:'Total users',activeNow:'Active now',idleUsers:'Idle users',newTickets:'New tickets',totalSpools:'Total spools',totalPrinters:'Total printers',remaining:'Remaining filament',usage30:'Usage 30 days',notifications:'Admin Notifications',notifyTicket:'Notify me for a new ticket',notifyUser:'Notify me when a new user registers',notifyOnline:'Notify me when a user becomes online',saveSettings:'Save settings',users:'Users',tickets:'Tickets'},ar:{totalUsers:'إجمالي المستخدمين',activeNow:'المستخدمون النشطون الآن',idleUsers:'المستخدمون الخاملون',newTickets:'التذاكر الجديدة',totalSpools:'إجمالي السبولات',totalPrinters:'إجمالي الطابعات',remaining:'الفلمنت المتبقي',usage30:'استهلاك 30 يوم',notifications:'إشعارات الأدمن',notifyTicket:'أرسل لي إشعار عند وصول تذكرة جديدة',notifyUser:'أرسل لي إشعار عند تسجيل مستخدم جديد',notifyOnline:'أرسل لي إشعار عندما يصبح مستخدم Online',saveSettings:'حفظ الإعدادات',users:'المستخدمون',tickets:'التذاكر'}};
  function token(){return sessionStorage.getItem('filaments_admin_token')||''} function t(k){return TR[lang]?.[k]||TR.en[k]||k}
  async function call(action,body={}){const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json','apikey':KEY,'x-admin-token':token()},body:JSON.stringify({action,...body})});const d=await r.json();if(!r.ok)throw new Error(d.message||d.error||'Request failed');return d}
  function fmtDate(v){if(!v)return'—';return new Date(v).toLocaleString(lang==='ar'?'ar-AE':'en-US')} function grams(v){const n=Number(v||0);return n>=1000?`${(n/1000).toFixed(2)} kg`:`${Math.round(n)} g`}
  function setLanguage(v){lang=v==='ar'?'ar':'en';document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';$('adminLanguage').value=lang;document.querySelectorAll('[data-k]').forEach(el=>el.textContent=t(el.dataset.k));$('adminSubtitle').textContent=lang==='ar'?'المستخدمون، النشاط، التذاكر والدعم':'Users, activity, tickets & support';$('refreshBtn').textContent=lang==='ar'?'تحديث':'Refresh';$('logoutBtn').textContent=lang==='ar'?'تسجيل خروج':'Log out';$('enableAdminNotifications').textContent=lang==='ar'?'تفعيل إشعارات المتصفح':'Enable browser notifications';renderUsers();renderFeedback()}
  function showAdmin(){$('loginView').classList.add('hidden');$('adminView').classList.remove('hidden')} function showLogin(){$('adminView').classList.add('hidden');$('loginView').classList.remove('hidden')}
  async function login(){const s=$('loginStatus');try{s.textContent='Signing in…';const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json','apikey':KEY},body:JSON.stringify({action:'login',username:$('adminUser').value.trim(),password:$('adminPass').value})});const d=await r.json();if(!r.ok)throw new Error(d.message||d.error||'Invalid credentials');sessionStorage.setItem('filaments_admin_token',d.token);showAdmin();await refresh()}catch(e){s.textContent=e.message}}
  function notify(title,body){if(Notification.permission==='granted')new Notification(title,{body,icon:'/icon.svg'})}
  function checkNotifications(){const snap={ids:new Set(users.map(u=>u.id)),active:new Set(users.filter(u=>u.active).map(u=>u.id)),tickets:new Set(feedback.map(f=>f.id))};if(!baseline){const saved=localStorage.getItem('fm_admin_baseline');if(saved){try{const b=JSON.parse(saved);baseline={ids:new Set(b.ids||[]),active:new Set(b.active||[]),tickets:new Set(b.tickets||[])}}catch{}}}
    if(baseline){if(prefs.notify_new_user)users.filter(u=>!baseline.ids.has(u.id)).forEach(u=>notify(lang==='ar'?'مستخدم جديد':'New user',`${u.nickname?u.nickname+' · ':''}${u.email}`));if(prefs.notify_new_ticket)feedback.filter(f=>!baseline.tickets.has(f.id)).forEach(f=>notify(lang==='ar'?`تذكرة جديدة #${f.ticket_no}`:`New ticket #${f.ticket_no}`,`${f.contact_email} · ${f.kind}`));if(prefs.notify_user_online)users.filter(u=>u.active&&!baseline.active.has(u.id)).forEach(u=>notify(lang==='ar'?'مستخدم أصبح Online':'User is online',`${u.nickname?u.nickname+' · ':''}${u.email} · ${fmtDate(u.last_seen)}`))}
    baseline=snap;localStorage.setItem('fm_admin_baseline',JSON.stringify({ids:[...snap.ids],active:[...snap.active],tickets:[...snap.tickets]}))}
  async function refresh(){try{const d=await call('dashboard');users=d.users||[];feedback=d.feedback||[];prefs=d.preferences||{};$('kTotal').textContent=d.stats?.total_users||0;$('kActive').textContent=d.stats?.active_users||0;$('kIdle').textContent=d.stats?.idle_users||0;$('kFeedback').textContent=d.stats?.feedback_new||0;$('kSpools').textContent=d.stats?.total_spools||0;$('kPrinters').textContent=d.stats?.total_printers||0;$('kGrams').textContent=grams(d.stats?.total_remaining_grams);$('kUsage').textContent=grams(d.stats?.usage_30d_grams);$('notifyNewTicket').checked=!!prefs.notify_new_ticket;$('notifyNewUser').checked=!!prefs.notify_new_user;$('notifyUserOnline').checked=!!prefs.notify_user_online;if(!sessionStorage.getItem('admin_lang_loaded')){setLanguage(prefs.language||'en');sessionStorage.setItem('admin_lang_loaded','1')}renderUsers();renderFeedback();checkNotifications()}catch(e){if(e.message==='unauthorized'){sessionStorage.removeItem('filaments_admin_token');showLogin()}else alert(e.message)}}
  function renderUsers(){const q=($('userSearch').value||'').toLowerCase(),state=$('userState').value;const rows=users.filter(u=>(!q||u.email.toLowerCase().includes(q)||String(u.nickname||'').toLowerCase().includes(q)||u.id.toLowerCase().includes(q))&&(state==='all'||(state==='active'&&u.active)||(state==='idle'&&!u.active)));$('usersBody').innerHTML=rows.map(u=>`<tr><td><span class="dot ${u.active?'active':'idle'}"></span>${u.active?(lang==='ar'?'نشط':'Active'):(lang==='ar'?'خامل':'Idle')}</td><td><input class="nick" data-id="${u.id}" value="${esc(u.nickname||'')}" placeholder="Nickname" style="min-width:120px"></td><td>${esc(u.email)}</td><td>${fmtDate(u.created_at)}</td><td>${fmtDate(u.last_seen)}</td><td>${esc(u.current_page||'—')}</td><td>${u.spools}</td><td>${grams(u.remaining_grams)}</td><td>${u.printers}</td><td>${u.printing}</td><td>${grams(u.usage_grams)}</td><td>${u.feedback}</td><td><div class="actions"><button class="btn secondary save-nick" data-id="${u.id}">${lang==='ar'?'حفظ الاسم':'Save nickname'}</button><button class="btn open-profile" data-id="${u.id}">${lang==='ar'?'فتح الملف':'Open profile'}</button></div></td></tr>`).join('')||`<tr><td colspan="13" class="muted">${lang==='ar'?'لا يوجد مستخدمون.':'No users found.'}</td></tr>`;document.querySelectorAll('.save-nick').forEach(b=>b.onclick=()=>saveNickname(b.dataset.id));document.querySelectorAll('.open-profile').forEach(b=>b.onclick=()=>location.href=`/admin-user.html?uid=${encodeURIComponent(b.dataset.id)}`)}
  async function saveNickname(id){const input=document.querySelector(`.nick[data-id="${id}"]`);await call('set_nickname',{user_id:id,nickname:input.value});await refresh()}
  function renderFeedback(){const f=$('feedbackFilter').value,rows=feedback.filter(x=>f==='all'||x.status===f||x.kind===f);$('feedbackList').innerHTML=rows.map(x=>`<div class="fitem"><div class="fhead"><b>Ticket #${x.ticket_no} · ${esc(x.contact_email)}</b><span class="tag">${esc(x.kind)}</span><span class="tag">${esc(x.status)}</span><span class="muted">${fmtDate(x.created_at)}</span></div><div class="msg">${esc(x.message)}</div><div class="actions"><button class="btn open-ticket" data-id="${x.id}">${lang==='ar'?'فتح التذكرة':'Open ticket'}</button><button class="btn secondary status-btn" data-id="${x.id}" data-status="read">${lang==='ar'?'تمت القراءة':'Mark Read'}</button><button class="btn secondary status-btn" data-id="${x.id}" data-status="in_progress">${lang==='ar'?'قيد المتابعة':'In Progress'}</button><button class="btn secondary status-btn" data-id="${x.id}" data-status="resolved">${lang==='ar'?'تم الحل':'Resolve'}</button></div></div>`).join('')||`<div class="muted">${lang==='ar'?'لا توجد تذاكر.':'No tickets found.'}</div>`;document.querySelectorAll('.status-btn').forEach(b=>b.onclick=()=>setStatus(b.dataset.id,b.dataset.status));document.querySelectorAll('.open-ticket').forEach(b=>b.onclick=()=>openTicket(b.dataset.id))}
  async function setStatus(id,status){try{await call('feedback_status',{id,status});if(currentTicket===id)await openTicket(id);await refresh()}catch(e){alert(e.message)}}
  async function openTicket(id){try{const d=await call('ticket_detail',{id});currentTicket=id;$('ticketModal').classList.add('show');$('ticketModalTitle').textContent=`Ticket #${d.ticket.ticket_no} · ${d.ticket.status}`;$('ticketModalInfo').textContent=`${d.ticket.contact_email} · ${d.ticket.kind} · ${fmtDate(d.ticket.created_at)}`;const all=[{sender:'user',message:d.ticket.message,created_at:d.ticket.created_at},...(d.messages||[])];$('ticketMessages').innerHTML=all.map(m=>`<div class="bubble ${m.sender}"><b>${m.sender==='admin'?(lang==='ar'?'الأدمن':'Admin'):(lang==='ar'?'المستخدم':'User')}</b><div>${esc(m.message)}</div><small class="muted">${fmtDate(m.created_at)}</small></div>`).join('')}catch(e){alert(e.message)}}
  async function reply(){const m=$('adminTicketReply').value.trim();if(!currentTicket||!m)return;await call('ticket_reply',{id:currentTicket,message:m});$('adminTicketReply').value='';await openTicket(currentTicket);await refresh()}
  async function savePrefs(){prefs={...prefs,language:lang,notify_new_ticket:$('notifyNewTicket').checked,notify_new_user:$('notifyNewUser').checked,notify_user_online:$('notifyUserOnline').checked};await call('save_admin_preferences',prefs);$('adminPrefsStatus').textContent=lang==='ar'?'تم الحفظ ✓':'Saved ✓';setTimeout(()=>$('adminPrefsStatus').textContent='',1500)}
  async function enableNotif(){if(!('Notification'in window))return alert(lang==='ar'?'المتصفح لا يدعم الإشعارات':'Notifications are not supported');const p=await Notification.requestPermission();alert(p==='granted'?(lang==='ar'?'تم تفعيل الإشعارات':'Notifications enabled'):(lang==='ar'?'لم يتم السماح بالإشعارات':'Notifications not allowed'))}
  async function logout(){try{await call('logout')}catch{}sessionStorage.removeItem('filaments_admin_token');showLogin()}
  function init(){$('adminLogin').onclick=login;$('adminPass').onkeydown=e=>{if(e.key==='Enter')login()};$('refreshBtn').onclick=refresh;$('logoutBtn').onclick=logout;$('userSearch').oninput=renderUsers;$('userState').onchange=renderUsers;$('feedbackFilter').onchange=renderFeedback;$('adminLanguage').onchange=e=>{setLanguage(e.target.value);savePrefs()};$('saveAdminPrefs').onclick=savePrefs;$('enableAdminNotifications').onclick=enableNotif;$('ticketModalClose').onclick=()=>$('ticketModal').classList.remove('show');$('adminReplyBtn').onclick=reply;$('ticketReadBtn').onclick=()=>setStatus(currentTicket,'read');$('ticketProgressBtn').onclick=()=>setStatus(currentTicket,'in_progress');$('ticketResolveBtn').onclick=()=>setStatus(currentTicket,'resolved');if(token()){showAdmin();refresh()}else showLogin();setInterval(()=>{if(token()&&!document.hidden)refresh()},60000)}init();
})();